# Example of the project template usage.

imports:
  - path: templates/project/project.py
    name: project.py

resources:
  - name: sourced-cftdemo-0
    type: project.py
    properties:
      parent:
        type: folder
        id: {{env.CFT_ORGANIZATION_FOLDER_ID}}
      billingAccountId: {{env.CFT_BILLING_ACCOUNT_ID}}
      activateApis:
        - compute.googleapis.com
        - deploymentmanager.googleapis.com
        - pubsub.googleapis.com
      serviceAccounts:
        - accountId: cft-demo-sa-0
          displayName: cft demo service account 0
          roles:
            - roles/editor
            - roles/viewer
            - {{env.CFT_PIPELINE_DEPLOYER_ROLE}}
          networkAccess: true
      usageExportBucket: false
