# Example of the project template usage.
#
# In this example, a project is created, along with some of the
# resources that an enterprise is likely to need for regular operations.
#
# Note that the `parent_type` property defaults to "organization", so it
# does not need to be specified in the config. It is specified here for
# informational purposes. Allowed values are 'organization' or 'folder'
#
# See `templates/project.py.schema` for detailed information on the
# properties.
#
# Replace the `parent_id` placeholder with your organization ID/folder ID.
# Replace the `billing_account_id` placeholder with your billing
# account ID.

imports:
  - path: templates/project/project.py
    name: project.py

resources:
  - name: {{CLOUD_FOUNDATION_TOOLKIT_PROJECT_NAME}}
    type: project.py
    properties:
      parent:
        type: {{CLOUD_FOUNDATION_TOOLKIT_PARENT}} # organization or folder
        id: {{CLOUD_FOUNDATION_TOOLKIT_FOLDER_ID}} # OrgID or folder ID
      billingAccountId: {{CLOUD_FOUNDATION_TOOLKIT_BILLING_ID}}
      activateApis:
        - compute.googleapis.com
        - deploymentmanager.googleapis.com
        - pubsub.googleapis.com
      serviceAccounts:
        - accountId: cft-demo-sa-0
          displayName: demo service account
          roles:
            - roles/editor
            - roles/viewer
            - {{CLOUD_FOUNDATION_TOOLKIT_PIPELINE_ROLE}}
          networkAccess: true
      usageExportBucket: true
      # sharedVPC: test-vpc-host-project
      # sharedVPCSubnets:
      #   - subnetId: subnet-1
      #     region: us-east1
